[tox]
minversion = 3.18.0
envlist = pep8,docs

[testenv]
usedevelop = True
deps =
  -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
  -r{toxinidir}/requirements.txt
passenv =
  http_proxy
  HTTP_PROXY
  https_proxy
  HTTPS_PROXY
  no_proxy
  NO_PROXY

[testenv:venv]
commands = {posargs}

[testenv:docs]
allowlist_externals = rm
commands =
  rm -rf doc/build
  sphinx-build -W -b html doc/source doc/build/html

[testenv:spelling]
deps =
   -r{toxinidir}/requirements.txt
   sphinxcontrib-spelling
   PyEnchant
commands = sphinx-build -b spelling doc/source doc/build/spelling

[testenv:pep8]
commands = flake8

[flake8]
show-source = True
ignore = E123,E125,D100
exclude=.venv,.git,.tox,dist,doc,*lib/python*,*egg,build
